---
title: "Регрессионный анализ"
output: html_notebook
---

```{r}
# Регрессионный анализ используется для определения типа зависимости
# и вычисления ее параметров.
```

```{r}
# Наиболее известная двумерная линейная регрессионная модель: Y’=b0+b1*x,
# где y’ – модельные (predicted) значения зависимой переменной y, 
# x – независимая переменная, 
# b0 и b1 – параметры модели (коэффициенты регрессии).
```

```{r}
# Такая модель позволяет оценить среднее значение переменной y при известном
# значении x.
```

```{r}
# Разность между истинным значением и модельным называется остатком (residual):
# d=Y’-Y.
```

```{r}
# Для того чтобы узнать значения параметров b0 и b1 применяют метод наименьших квадратов.
```

```{r}
# Для проверки нулевой гипотезы о том,
# что между переменными не существует линейной зависимости,
# используется F-статистика (статистика Фишера).
# Если полученное р-значение (уровень значимости) меньше 0.05,
# то гипотезу отвергаем, т.е. между переменными существует линейная зависимость.
```

```{r}
# Далее, если гипотезу отвергли,
# необходимо оценить адекватность построенной модели с помощью анализа остатков.
# К остаткам выдвигается три требования:
# остатки должны быть нормально распределены,
# независимы и численно малы.
# Если все три требования выполняются,
# следовательно, модель хорошо подходит к исходным данным,
# т.е. адекватно описывает данные.  
```

# Задание

```{r}
# 1

# Открыть таблицу данных trees из библиотеки datasets,
# содержащую замеры диаметра, высоты и объема вишневых деревьев.

datasets::trees
```

```{r}
# 2

# Выведите имена столбцов таблицы trees.

names(trees)
```
```{r}
# 2.1

# Постройте корреляционную матрицу по таблице trees.

# С помощью полученных коэффициентов корреляции определите,
# между какими переменными существует линейная зависимость
# (сильная или слабая, прямая или обратная).

cor(trees)
```
```{r}
# 3

# Постройте графики зависимостей.
# Для этого разбейте окно графика на три части (функция par()),
# и в каждой части создайте график зависимости.

par(mfrow = c(3, 1))
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Height)
plot(trees$Volume, trees$Height)
```

```{r}
# 4

# Проведите регрессионный анализ для определения существования
# линейной зависимости между объемом вишневых деревьев(y)
# и диаметром(x1) c высотой (x2).
# Запишите уравнение зависимости с полученными коэффициентами регрессии.
# Выведите график зависимости.

lm.p<-lm(trees$Volume~trees$Girth + trees$Height)
summary(lm.p)
```

```{r}
# уравнение зависимости с полученными коэффициентами регрессии

# trees$Volume = -57.9877 + 4.7082  * trees$Height + 0.3393 * trees$Height
```

```{r}
# график зависимости

plot(lm.p)
```






```{r}
# 5

# Чему равен полученный коэффициент детерминации? Поясните смысл полученного численного значения.

# Multiple R-squared: 0.948
# Множественный коэфициент детерминации означает,
# что модель объясняет 94.8 % дисперсии значений веса.
```

```{r}
# 6

# Проведите анализ остатков для проверки адекватности построенной регрессионной модели.

r1<-residuals(lm.p)
data.frame(r1)
d1<-data.frame(trees$Volume,predict(lm.p),r1)
d1
```

```{r}
# 7

# Сделайте вывод по результатам проведенного регрессионного анализа.

# На первом графике остатки распределены хаотично, и мы не видим
# между ними зависимости. 

# Если допущение нормальном распределение остатков выполняется,
# то точки на диаграмме Normal Q-Q должны ложиться на прямую.
# Поскольку это не наблюдается, это допущение не выполняется.

# Наблюдается остатки > 5-10% от наблюдаемых значений

# Вывод: построенная модель не подходит для описания исходных данных.
```


```{r}
# 8

# Откройте таблицу Turtle.csv c данными по длине, ширине,
# высоте и весу черепах.

Turtle <- read.csv("Turtle.csv", sep= ";", header = TRUE )
Turtle
```


```{r}
# 9

# С помощью теста Шапиро-Уилка проверьте на нормальность каждый столбец таблицы. Сделайте выводы.

shapiro.test(Turtle$length)
shapiro.test(Turtle$width)
shapiro.test(Turtle$height)
shapiro.test(Turtle$weight)
```
```{r}
# Данные в каждом столбце распределены нормально,
# так как p-value везде > 0.05, и мы не можем отклонить нулевую гипотезу
```

```{r}
# 10

# Постройте корреляционную матрицу по данным таблицы Turtle.
# Определите значимые зависимости.

cor(Turtle)
```
```{r}
# видим значимые зависимости между длиной, шириной, высотой и весом
```

```{r}
# 11

# Проведите регрессионный анализ для определения существования линейной зависимости между весом (weight) черепах и другими параметрами
# (length, width, height). Сделайте вывод по результатам анализа.

lm.turtle <-lm(Turtle$weight~., data = Turtle)
summary(lm.turtle)
```

```{r}
# график зависимости

plot(lm.turtle)
```
```{r}
# анализ остатков
r_turtle <-residuals(lm.turtle)
data.frame(r_turtle)
d_turtle <-data.frame(Turtle$weight,predict(lm.turtle),r_turtle)
d_turtle
```


```{r}
# Сделайте вывод по результатам проведенного регрессионного анализа.

# На первом графике остатки распределены хаотично, и мы не видим
# между ними зависимости. 

# Если допущение нормальном распределение остатков выполняется,
# то точки на диаграмме Normal Q-Q должны ложиться на прямую.
# Поскольку это не наблюдается, это допущение не выполняется.

# Все остатки < 5-10% от наблюдаемых значений

# Вывод: построенная модель подходит для описания исходных данных.
```

