---
title: "Задание 7_3. Бинарная регрессия R"
output: html_notebook
---

# Задание

```{r}
# Откройте таблицу данных datlg (медицинские данные по кардиологии:
# y – зависимая переменная – стоит делать операцию пациенту или нет
# в зависимости от имеющихся предикторов).
# Нужно построить логит и пробит модели и сравнить полученные результаты.
```

```{r}
datlg <- read.csv("datlg.csv", sep = ",", header = TRUE)
```

```{r}
# Сначала преобразуем зависимую переменную в категориальную.

datlg$y <- factor(datlg$y)	
```

```{r}
str(datlg)
```

```{r}
# Н0: Между переменными не существует логистической зависимости.
```


```{r}
# строи логит регрессию
mylogit <- glm(y ~ sex + x1 + x2 + x3 + x4, data = datlg,
               family= binomial("logit"))
```

```{r}
# Для вывода результатов используем следующую функцию:

summary(mylogit); AIC(mylogit)
```

```{r}
# Получим результаты:

# Значимыми являются переменные  x1, x2
# У них p-value < 0.05

# Статистика критерия отношения правдоподобия равна:
# 389.75 - 327.06 = 62, 69
# Статистика критерия попадает в критическую область, следовательно,
# следует отвергнуть гипотезу о статистической незначимости 
# построенного уравнения
```


```{r}
# Проверим занчимость логит модели в целом

#install.packages("aod")

library(aod)

wald.test(b = coef(mylogit), Sigma = vcov(mylogit),
          Terms = 1:6)
```

```{r}
# так p-value < 0.05, то уравнение логит регрессии значимо в целом
```

```{r}
# пробит регрессия 

myprobit <- glm(y ~ sex + x1 + x2 + x3 + x4, data = datlg,
                family= binomial("probit"))
summary(myprobit); AIC(myprobit)
```


```{r}
# Можно говорить о статистической значимости коэффициентов x1, x2
# Их p-value < 0.05

# Статистика критерия отношения правдоподобия равна:

# 389.75 - 327.71 = 62,04

# Статистика критерия попадает в критическую область, следовательно, 
# следует отвергнуть гипотезу гипотезу о ститистической незначимости 
# построенного уравнения пробит-регрессии

# Значение AIC для пробит модели больше, чем для логит модели, поэтому 
# можно сделать вывод, что логит модель более адекватна 

```

```{r}
# Проверим значимость пробит модели в целом

wald.test(b = coef(myprobit), Sigma = vcov(myprobit),
          Terms = 1:6)
```

```{r}
# p-value < 0.05
# Это значит, что уравнение пробит модели значимо в целом
```

