---
title: "Задание 3"
output: html_notebook
---

```{r}
#Рассмотрим динамику изменения оценок по теории вероятностей и математической статистике за последние два года: оценки по стобалльной, по пятибалльной и по европейской (буквенной) системам.
```

```{r}
#Имеются два массива данных: год1 и год2, длиной 52 и 61 соответственно.
```

```{r}
first<-c(83,70,86,51,61,67,80,84,70,64,83,55,88,75,61,70,95,52,75,92,86,89,83,58,51,
65,87,54,90,62,67,66,83,65,70,87,69,51,51,60,52,74,80,79,85,85,92,22,92,57,84,92)

second <- c(70,31,70,46,78,69,36,33,65,70,74,51,90,26,62,70,86,86,80,33,55,31,69,31,62,
63,86,55,69,62,31,90,31,31,69,64,57,75,53,89,0,31,81,53,86,52,98,58,31,69,
69,51,75,39,0,56,51,69,46,41,65)
```

```{r}
#Выделим следующие категории:
#• по пятибалльной системе: 2 — баллы от 0 до 50, 3 — от 51 до 68, 4 —
#от 69 до 85 и 5 — от 86 до 100;
#• по европейской системе: F — от 0 до 30, FX — от 31 до 50, E — от 51
#до 60, D — от 61 до 68, C — от 69 до 85 , B — от 86 до 95, A — от 96
#до 100.
```

```{r}
#1

#Воспользуйтесь функцией cut() для построения первого вектора данных (разбиение1_1) по пятибалльной системе и построения второго вектора (разбиение1_2) по европейской системе с подписями категорий для массива данных год1.
```

```{r}
cut1_1 <- cut(first, breaks = c(0, 50, 68, 85, 100), labels = c("2", "3", "4", "5"))
cut1_2 <- cut(first, breaks = c(0, 30, 50, 60, 68, 85, 95, 100), labels = c("F", "FX", "E",
                                                                            "D", "C", "B", "A"))
```

```{r}
cut1_1
cut1_2
```
```{r}
#Команда cut создает факторы, разделив область вариации числового вектора x на интервалы:
#cut(x, breaks, labels),
#где в качестве аргумента breaks может выступать либо необходимое число интервалов,
#либо вектор, содержащий список "точек разрыва", а labels определяет названия
#уровней. 

#Пример:
#cut(x, breaks=3, labels = letters[1:3])

#[1] a a b b b a b b b c c
#Levels: a b c

#cut(x,breaks=quantile(x,c(0,.25,.50,.75,1)),
#labels=c("Q1","Q2","Q3","Q4"),include.lowest=TRUE)

#[1] Q1 Q1 Q2 Q2 Q3 Q1 Q2 Q2 Q3 Q4 Q4
#Levels: Q1 Q2 Q3 Q4
```

```{r}
#Во втором фрагменте  числовой вектор "разрезан" по квартильным значениям,
#а параметр include.lowest указан, чтобы избежать появления неопределенности
#“NA“ для значения х = 1.
```

```{r}
#2

#Таким же образом создайте вектор данных (разбиение2_1) по пятибалльной системе и вектор данных (разбиение2_2) по европейской системе с подписями категорий для массива данных год2.
```

```{r}
cut2_1 <- cut(second, breaks = c(0, 50, 68, 85, 100), labels = c("2", "3", "4", "5"),
                     include.lowest=TRUE)
cut2_2 <- cut(second, breaks = c(0, 30, 50, 60, 68, 85, 95, 100), labels = c("F", "FX", "E",
                                                                            "D", "C", "B", "A"),
                     include.lowest=TRUE)

cut2_1
cut2_2
```
```{r}
#3

#Определите число элементов, попавших в построенные категории для пятибалльной системы оценок:

#А) создайте таблицу (таблица1_1) для подсчета частоты каждой категории оценок вектора разбиение1_1;  (функция table())

#В) создайте таблицу (таблица2_1) для подсчета частоты каждой категории оценок вектора  разбиение2_1.
```


```{r}
tab1_1 <- table(cut1_1)
tab1_1
```

```{r}
tab2_1 <- table(cut2_1)
tab2_1
```

```{r}
#4. 

#Определите число элементов, попавших в построенные категории для европейской системы оценок:

#А) создайте таблицу (таблица1_2) для подсчета частоты каждой категории оценки вектора разбиение1_2;

#В) создайте таблицу (таблица2_2) для подсчета частоты каждой категории (оценки) вектора разбиение2_2.
```

```{r}
tab1_2 <- table(cut1_2)
tab1_2
```

```{r}
tab2_2 <- table(cut2_2)
tab2_2
```


```{r}
#5

#Для каждого разбиения постройте таблицы относительных частот следующим образом:
#> table(разбиение1_1)/length(разбиение1_1)

table(cut1_1)/length(cut1_1)

table(cut2_1)/length(cut2_1)

table(cut1_2)/length(cut1_2)

table(cut2_2)/length(cut1_2)
```

```{r}
#6

#Постройте мозаичные диаграммы по созданным четырем таблицам таблица1_1 —таблица2_2
#с помощью функции barplot(), т.е. когда height — числовой вектор. Разделите окно графика на 4 части (par(mfrow=c(2,2)).
#Пример:   barplot(height=таблица 1_1)

par(mfrow = c(2, 2))
barplot(height = tab1_1)
barplot(height = tab2_1)
barplot(height = tab1_2)
barplot(height = tab2_2)
```
```{r}
#Функция cbind() (от сolum и bind – столбец и связывать) или rbind() (от row и bind – строка и связывать) позволяет собрать матрицу из нескольких векторов.

#Например:
# Объединим векторы при помощи функции cbind():
#cbind(a, b, d, e)

#      a   b   d    e
#[1,] 1   5   9   13
#[2,] 2   6  10  14
#[3,] 3   7  11  15
#[4,] 4   8  12  16

# Объединим те же векторы при помощи функции rbind():
#rbind(a, b, d, e)
# [,1] [,2] [,3] [,4]
#a 1     2    3    4
#b 5    6    7     8
#d 9   10  11   12
#e 13 14  15   16
```


```{r}
#8

#Создайте матрицу (матрица1), объединив таблица1_1 и таблица2_1 используя функцию cbind().

m1 <- cbind(tab1_1, tab2_1); m1
```

```{r}
m2 <- cbind(tab1_2, tab2_2); m2
```

```{r}
#9

#Постройте мозаичные диаграммы по созданным матрицам (матрица1 и матрица2) с помощью функции barplot(), когда height — числовая матрица
#и beside = FALSE, разбив окно графика на 2 элемента (функция par()).

#Пример:   barplot(height=таблица3, beside=FALSE)

par(mfrow = c(2, 1))
barplot(height = m1, beside = FALSE )
barplot(height = m2, beside = FALSE )
```

```{r}
#10.

#Постройте круговые диаграммы для таблиц таблица1_1 —таблица2_2, используя функцию pie() c аргументами: labels=c(), radius=1, col=c(), main=” ”; и разбив окно графика на 4 элемента (функция par()).

#Пример:
#pie(table1, labels=c(“2”,”3”,”4”), radius=1, col=c(5,15,26), main=” table1”)

par(mfrow = c(2, 2))
pie(tab1_1, labels=c("2","3","4", "5"), radius=1, col=c(5, 10, 15, 20, 25), main= "First_year five_point scale")
pie(tab2_1, labels=c("2","3","4", "5"), radius=1, col=c(5, 10, 15, 20, 25), main= "Second_year five_point scale")
pie(tab1_2, labels=c("F","FX","E", "D", "C", "B", "A"), radius=1, col=c(5, 10, 15, 20, 25, 30, 40), main= "First_year european_scale")
pie(tab2_2, labels=c("F","FX","E", "D", "C", "B", "A"), radius=1, col=c(5, 10, 15, 20, 25, 30, 40), main= "Second_year european_scale")
```



