---
title: "Таблицы сопряженности в R"
output: html_notebook
---

```{r}
# Пакет MASS содержит данные о 93 автомобилях,
# поступивших в продажу в США в 1993 году. Они хранятся в объекте Cars93 и
# включают 27 признаков для каждого автомобиля,
# некоторые из которых являются категориальными. Загрузите пакет MASS.
```


```{r}
install.packages("MASS")
```
```{r}
library(MASS)
```

```{r}
View(Cars93)
```

```{r}
Cars93$Type
```

```{r}
# В таблице 6 типов автомобилей. Функция table() сообщает,
# сколько у нас их каждого типа:
table(Cars93$Type)
```

```{r}
# Функция prop.table() преобразует их в доли:
prop.table(table(Cars93$Type))
```

```{r}
# То же самое с происхождением автомобилей:
table(Cars93$Origin)
```

```{r}
prop.table(table(Cars93$Origin))
```
# Как создать таблицу сопряженности признаков в R

```{r}
# Набор данных Cars93 содержит
# одинаковое количество автомобилей из США и не из США,
# и наиболее распространенными типами являются Midsize и Small.

# Давайте посмотрим на типы автомобилей с точки зрения их происхождения.
# Можно снова использовать table(), но теперь с двумя аргументами.
# Первый станет переменной строки, а второй станет переменной столбца:

# В таблице показано совместное распределение
# двух категориальных переменных (Type и Origin).
# Такие таблицы называются таблицами сопряженности.

tab1 <- table(Cars93$Type, Cars93$Origin);tab1
```

```{r}
# Функции rowSums() и colSums() рассчитывают суммы по столбцам и строкам.

rowSums(tab1)

colSums(tab1)
```

# Как получить проценты из таблицы сопряженности?

```{r}
# Функция prop.table(), вложенная в table(), дает частоты:

prop.table(table(Cars93$Type, Cars93$Origin))
```

```{r}
# Преобразование в проценты - это просто умножение на 100:

# Обратите внимание, что это совместное распределение вероятностей,
# из которого мы видим, например, что около 7,5% автомобилей
# являются небольшими и имеют американское происхождение.

prop.table(table(Cars93$Type, Cars93$Origin))*100
```

```{r}
# Чаще всего нас интересует распределение одной переменной внутри групп,
# созданных другой. Здесь интересным представляется распределение типов
# автомобилей среди американских и (отдельно) неамериканских автомобилей.
# Чтобы получить это, мы используем аргумент margin для функции prop.table().
# Он сообщает, где в строках (margin = 1) или в столбцах (margin = 2) переменная группировки:


# Теперь мы можем легко увидеть,
# что маленькие автомобили встречаются за пределами США в два раза чаще,
# чем в США.
# Также обратите внимание, что проценты составляют до 100 в столбцах, тогда как в объединенной таблице распределения (таблица без аргумента margin) 100 представляла собой сумму всей таблицы.

tab2<-prop.table(table(Cars93$Type, Cars93$Origin), margin=2)*100
tab2
```

```{r}
# Теперь мы можем легко увидеть,
# что маленькие автомобили встречаются за пределами США в два раза чаще,
# чем в США.

# Также обратите внимание, что проценты составляют до 100 в столбцах, тогда как в объединенной таблице распределения (таблица без аргумента margin) 100 представляла собой сумму всей таблицы.

colSums(tab2)
```

# Критерий хи-квадрат


```{r}
# Наиболее распространенный вопрос,
# который возникает в таблицах сопряженности, заключается в том,
# являются ли переменные строк и столбцов независимыми.
# Самый простой способ ответить на него - запустить тест хи-квадрат.
# Одно из условий применимости критерия состоит в том,
# что ожидаемые частоты в любой из ячеек таблицы сопряженности не должны
# быть меньше 5.
```


```{r}
# Давайте проверим, являются ли переменные Type и Origin независимыми:

chisq.test(Cars93$Type, Cars93$Origin)
```
```{r}
# По-видимому, это не так, но мы также получили предупреждение хи-квадрат.
# Это связано с тем, что статистика хи-квадрат следует распределению хи-квадрат
# только приблизительно. Чем больше наблюдений мы имеем,
# тем лучше приближение.
# Функция chisq.test выдает вышеупомянутое предупреждение всякий раз,
# когда одно из ожидаемых значений меньше 5.
```

# Задание

```{r}
# Предположим, мы выполнили исследование трех популяций наземных моллюсков,
# в ходе которого отмечали цвет раковины.
# Цвет выражался следующими тремя градациями -
# "светлый" (light),
# "темный" (dark)
# и "очень темный" (very dark). 
```

```{r}
# Необходимо выяснить, различаются ли частоты встречаемости каждого из вариантов окраски в исследованных популяциях.
```

```{r}
#Учтенные частоты выражаются следующими значениями:

light <- c(12, 40, 45)
dark <- c(87, 34, 75)
very.dark <- c(3, 8, 2)

# С начало нужно собрать все три вектора в одну матрицу, проверить нулевую гипотезу с помощью критерия хи-квдрат и описать полученный результат. 
m1 <- matrix(c(light, dark, very.dark), 3, 3)
```

```{r}
m1
```

```{r}
chisq.test(m1)
```
# Точный тест Фишера

```{r}
#Т очный критерий Фишера является альтернативой критерию хи-квадрат,
# используемой в основном, когда аппроксимация хи-квадрат не является удовлетворительной. При небольшом числе наблюдений более корректным подходом
# (с точки зрения получаемых р-значений) будет использование точного теста Фишера (Fisher’s exact test).
# Он основан на переборе всех возможных вариантов заполнения таблицы
# сопряженности при имеющейся численности групп,
# и поэтому чем эта численность меньше, тем проще выполнить соответствующие вычисления.
```

```{r}
# Пример

X <- matrix(c(1, 10, 8, 4), ncol = 2)#таблица сопряженности 
X

# Полученное значение p-value = 0.009423<0.05, таким образом, нулевую гипотезу отклоняем. Признаки зависимы.
fisher.test(X)
```

```{r}
# Особое место отводится точному критерию Фишера в медицине. Это важный метод обработки медицинских данных, нашедший свое применение во многих научных исследованиях. Благодаря ему можно исследовать взаимосвязь определенных
# фактора и исхода, сравнивать частоту патологических состояний между разными
# группами пациентов и т.д.
```

# Задание 

```{r}
# С помощью точного критерия Фишера проверьте гипотезу о независимости Type и Origin из таблицы Cars93
```

```{r}
fisher.test(Cars93$Type, Cars93$Origin)
```
# G-тест

```{r}
# Другой альтернативой является так называемый G-тест. Его статистика также приблизительно распределена по хи-квадрат, но для небольших выборок это
# приближение лучше, чем при использовании теста хи-квадрат. Для G-теста мы можем использовать функцию GTest из пакета DescTools. 
```

```{r}
# Примените G-теста для проверки независимости переменных Type и Origin.
GTest(Cars93$Type, Cars93$Origin)
```
# Таблица размерности 3 (или больше)

```{r}
# Давайте посмотрим на Man.trans.avail, Origin и Type одновременно.
# Функция table() разбивает набор данных в соответствии с переменной,
# представленной как третья:

table(Cars93$Man.trans.avail, Cars93$Origin, Cars93$Type)
```

```{r}
# Функция ftable() дает более компактный вид:

ftable(Cars93$Man.trans.avail, Cars93$Origin, Cars93$Type)
```
# Тест Кокрана-Мантеля-Хензеля (англ. "Cochran-Mantel-Haenszel test" или просто "CMH test")

```{r}
# Из приведенных выше результатов ясно,
# что зависимость между Origin и Man.trans.avail отличается от Type.
# Чтобы учесть возможные различия, можно использовать критерий Кохрана-Мантеля-Хензеля:

mantelhaen.test(Cars93$Man.trans.avail, Cars93$Origin, Cars93$Type)
```
# Задание
```{r}
# Имеются результаты исследования эффективности действия мази,
# содержащей новое действующее вещество,
# в отношении определенного инфекционного заболевания.
# Дизайн экперимента заключался в следующем: две группы испытуемых подвергались лечению при помощи нового препарата и плацебо.
# В конце эксперимента учтено количество случаев
# успешного и неуспешного лечения в обоих группах.
# Эксперимент был повторен по описанной схеме в 8 медицинских центрах.

drug <-array(c(11, 10, 25, 27,16, 22, 4, 10,
          14, 7, 5, 12,2, 1, 14, 16,
          6, 0, 11, 12,1, 0, 10, 10,
          1, 1, 4, 8,4, 6, 2, 1),
        dim = c(2, 2, 8),dimnames = list(
          Group = c("Drug", "Control"),
          Response = c("Success", "Failure"),
Center = c("1", "2", "3", "4", "5", "6", "7", "8")))
drug
```
```{r}
# При помощи CMH-критерия проверьте нулевую гипотезу,
# что между двумя анализируемыми качественными признаками (в нашем случае "экспериментальная группа" и "исход лечения") нет никакой связи.

mantelhaen.test(drug)
```





