---
title: "Расчет описательных статистик"
output: html_notebook
---

```{r}
#создаем вектор, в котором "Male"/"Female" повторяется 50 раз
sex <- rep(c("Male", "Female"), 50); sex

#создаем вектор ,в котором возраст от 1 до 16 повторяется 7 раз
age <- rep(c(1:16),7); age

#проверяем сколько значений в векторе age
length(age);

#если значений больше 100, то оставляем только первые 100
age <-  head(age, 100)

#создаем вектор температур тела от 36 до 39 с шагом 0.2
#повторяем значения 7 раз
temp <-  rep(seq(36, 39, 0.2), 7)

#проверяем количество температур
length(temp);

#если количество температур больше 100, то оставляем только первые 100
temp <-  head(temp, 100)

#создаем таблицук с полом, возрастом и температурами
data1 <-  data.frame(sex, age, temp); data1
```

```{r}
#смотрим на структуру тиблицы data1
str(data1)
```


```{r}
#расчитываем средний возраст
mean(age)

#находим медиану по возрасту
median(age)

#расчитываем дисперсию по возрасту
var(age)

#расчитываем стандартное отклонение по возтрасту
sd(age)

#находим минмальный возраст
min(age)

#находим максимальный возраст
max(age)

#находим кванитили
quantile(age)
```

```{r}
# при этом среднее, минимальное, максимальное и кванитили можно посмотреть одной командой 
summary(age)
```


```{r}
#можем получить информацию отдельно по мужскому полу
summary(data1$age[data1$sex == "Male"])
```
```{r}
#либо отдельно по женскому полу
summary(data1$age[data1$sex == "Female"])
```


```{r}
#устанавлиеваем пакет moments. В нем есть функции для определения коэфициента крутости и коэфициента ассиметрии
install.packages("moments")
```

```{r}
#подключаем установленный пакет moments
library(moments)
```

```{r}
#Коэффициент крутости и ассиметрии при нормальном распределении должны быть близки нулю.
#Допустимое отклонение 0.05
```


```{r}
#Рассчитываем коэффициенты крутости для возраста
kurtosis(age)
```

```{r}
#расчитываем коэфициент ассиметрии
skewness(age)
```

```{r}
# в нашем случае и коэфициент крутости и ассиметрии больше, чем 0.05
# это значит, что распределение возраста не является нормальным
# визуально это выглядит так
plot(density(age), col = "red", ylim = c(0, 0.1))
```


```{r}
# делаем разбиение возраста на интервалы: от 0 до 3, от 4 до 7, от 8 до 14, от 15 до 17
# присваем каждому инетрвалу свою метку(labels)
age1 <-  cut(age, breaks = c(0, 3, 7, 14, 17), labels = c("1", "2", "3", "4"));age1
```
```{r}
#выводим разбиение в виде таблицы
table(age1)
```


```{r}
# теперь разбиваем температуру: от 0 до 37, от 37 до 38, от 38 до 39
temp1 = cut(temp, breaks = c(0, 37, 38, 39))

#выводим разбиение в виде таблицы
table(temp1)
```

```{r}
# функция tapply позволяет применить функцию к конкретному столбцу
# в данном случае применяем функцию summary для стобца sex таблицы data1
tapply(data1$temp, INDEX = data1$sex, FUN = summary )
```

```{r}
#находим индекс минимальной температуры
which.min(data1$temp)

#находим индекс максимальной температуры
which.max(data1$temp)
```
```{r}
#смотрим по индексу, какая температура является минимальной
data1$temp[1]
```

```{r}
#смотрим по индексу, какая температура является максимальной
data1$temp[16]
```


```{r}
#для редактирования таблицы можно возмользоваться функцией edit
edit(data1)
```


```{r}
#чтобы посмотреть на таблицу можно возпользоваться функцией View
View(data1)
```


```{r}
# из набора данных mtcars выодим название машины с минимальным mpg
rownames(mtcars)[which.min(mtcars$mpg)]

#из набора данных mtcars выводим названме машины с максимальным mpg
rownames(mtcars)[which.max(mtcars$mpg)]
```

## Недостающие данные NA

```{r}
# создаем пропущенное значенме в наборе данных mtcars
mtcars$mpg[3] <- NA

# теперь, чтобы подсчиать, например, среднее мы должны использовать na.rm = TRUE
#чтобы пропущенное значение пропускалось при расчете
mean(mtcars$mpg, na.rm = TRUE)
```

```{r}
# создаем новый набор данных из данных mtcars
#в новом наборе будут удалены строки с пропущенными значениями
cars <-  na.omit(mtcars)
```

```{r}
# сравнваем количество строк в mtcars и cars
# видим, что она уменьшилась на 1
length(mtcars$mpg)
length(cars$mpg)
```

## Выбросы

Значения, которые выходят за пределы допустимых.


```{r}
# строим ящик с усами для набора данных mtcars
# видим, что есть выбросы
# но чтобы проверить, действительно ли это выбросы, нужно использовать специальные статичтические критерии 
boxplot(mtcars$mpg)
```


```{r}
# устанавлиемваем пакет outliers
# в этом пакете есть критерий Граббса
install.packages("outliers")
```

```{r}
# подключаем скачанный пакет outliers
library(outliers)
```

```{r}
#Чтобы по критерию Граббса определить, есть ли выбросы в нашенм наборе данных, нужно определить нулевую гипотезу. В нашем случае нулевая гипотеза будет такова: "В наборе данных mtcars нет выбросов"

#Чтобы подтвердить нулевую гипотезу, мы должны получить p-value(уровень значимости) больше 0.05.

#p-value показывает вероятность ошибиться при отклонении нулевой гипотезы
#то есть допустить ошибку первого рода
```


```{r}
# применяем критерий Граббса
# p-value > 0.05
# Это значит, что в наборе данных mtcars нет выбросов
# несмотря на то, что они были на диаграмме boxplot
grubbs.test(mtcars$mpg)
```

```{r}
# также мы можем проверить нулевую гипотезу с помощью теста Диксона
# тест Диксона принимает на вход только 30 значений, у нас данных больше
# поэтому делаем срез от 5 до 34
# p-value по-пржнему > 0.05
dixon.test(mtcars$mpg[5:34])
```





















