---
title: "Задание 7.2"
output: html_notebook
---

# Подбор вида зависимости между переменными

```{r}
# 1. Откройте файл данных Osvech.csv.

Osvech <- read.csv("Osvech.csv", sep = ";", header = TRUE)
Osvech
```

```{r}
# 2. Постройте график зависимости температуры от глубины.

plot(Osvech$temperatura, Osvech$glubina, , type = "o")
```

```{r}
# 3. Проведите регрессионный анализ для проверки следующих видов зависимостей
#между переменными - температура и глубина:

# а) линейная зависимость(y=a0+a1*x);
# б) полиномиальная зависимость второй степени(y=a0+a1*x+a2*x^2);
# в) логарифмическая зависимость (y=ao*log(x)).
fit1 <- lm(temperatura~glubina, data = Osvech)

fit2 <- lm(temperatura~glubina + I(glubina^2), data = Osvech)

fit3 <- lm(temperatura~log(glubina), data = Osvech)
```

```{r}
# Проверим гипотезу о существовнии линейной зависимости между
# температурой и глубиной
summary(fit1)
```

```{r}
# Multiple R-squared:  0.8078
# Множественный коэфициент детерминации означает,
# что  80.78 % отклонений от средней зависимой переменной будет
# учтено в построенной модели.
```

```{r}
# уравнение зависимости с полученными коэффициентами регрессии

# Osvech$temperatura = 12.42952 -0.25500  * Osvech$glubina
```


```{r}
# график зависимости
plot(fit1)
```

```{r}
# на первом графике остатки не распределены хаотично
# мы видим между ними некоторую зависимость
```

```{r}
# # Если допущение нормальном распределение остатков выполняется,
# то точки на диаграмме Normal Q-Q должны ложиться на прямую.
# Поскольку это не наблюдается, это допущение не выполняется.
```

```{r}
# Проведем анализ остатков для проверки адекватности
# построенной регрессионной модели.

r1<-residuals(fit1)
data.frame(r1)
d1<-data.frame(Osvech$temperatura,predict(fit1),r1)
d1

```

```{r}
# # Наблюдаются остатки > 5-10% от наблюдаемых значений

# Вывод: модель плохо походит для анализа исходных данных
```

```{r}
# Проверим гипотезу о существовнии полиномиальной зависимости второй степени между
# температурой и глубиной
summary(fit2)
```

```{r}
# Multiple R-squared: 0.9649
# Множественный коэфициент детерминации означает,
# что модель объясняет 96.4 % дисперсии значений веса.
```

```{r}
# уравнение зависимости с полученными коэффициентами регрессии

# Osvech$temperatura = 15.922798 - 0.931586  * Osvech$glubina +  0.027470 * I(glubina^2)
```

```{r}
# график зависимости

plot(fit2)
```


```{r}
# # На первом графике остатки распределены хаотично, и мы не видим
# между ними зависимости. 

# Если допущение нормальном распределение остатков выполняется,
# то точки на диаграмме Normal Q-Q должны ложиться на прямую.
# Поскольку это не наблюдается, это допущение не выполняется.
```

```{r}
# Проведем анализ остатков для проверки адекватности
# построенной регрессионной модели.

r2 <-residuals(fit2)
data.frame(r2)
d2<-data.frame(Osvech$temperatura,predict(fit2),r2)
d2
```

```{r}
# # # Не наблюдаются остатки > 5-10% от наблюдаемых значений

# Вывод: модель походит для анализа исходных данных
```

```{r}
# Проверим гипотезу о существовнии логарифмической зависимости между
# температурой и глубиной
summary(fit3)
```

```{r}
# Multiple R-squared:  0.9228
# Множественный коэфициент детерминации означает,
# что  92.2 % отклонений от средней зависимой переменной будет
# учтено в построенной модели.
```

```{r}
# уравнение зависимости с полученными коэффициентами регрессии

# Osvech$temperatura = 16.4756 - -2.9744   * log(glubina)
```

```{r}
# график зависимости

plot(fit3)
```

```{r}
# На первом графике остатки не распределены хаотично, и мы видим
# некоторую зависимость. 

# Если допущение нормальном распределение остатков выполняется,
# то точки на диаграмме Normal Q-Q должны ложиться на прямую.
# Поскольку это не наблюдается, это допущение не выполняется.
```

```{r}
# Проведем анализ остатков для проверки адекватности
# построенной регрессионной модели.

r3 <-residuals(fit3)
data.frame(r3)
d3<-data.frame(Osvech$temperatura,predict(fit3),r3)
d3
```

```{r}
# # Наблюдаются остатки > 5-10% от наблюдаемых значений

# Вывод: модель плохо походит для анализа исходных данных
```


```{r}
# Сравнить полученные результаты попарно с помощью функции
# anova(object1, object2, object3).

# Какая регрессионная модель больше подходит к данным и почему.

anova(fit1, fit2)

anova(fit1, fit3)

anova(fit2, fit3)
```

```{r}
# Результат сравнения fit1 и fit2 значим.
# Это значит, что модель fit1 имеет более высокую предсказательную способность.

# Результат сравнения fit2 и fit3 значим.
# Это значит, что модель fit2 имеет более высокую предсказательную способность.

# Вывод: модель fit1 лучше подходит к данным, так как имеет наиболее высокую
# предсказательную способность
```

```{r}
# # Воспользуемся функцией gvlma() из пакета gvlma в программе RStudio
# для общей проверки выполнения всех требований,
# лежащих в основе линейной регрессионной модели,
# включая отдельно оценки асимметрии, эксцесса и гомоскедастичности.

gvlma(fit1)
```
```{r}
# Из результатов теста (строка Global Stat) следует, что данные удовлетворяют
# всем статистическим допущениям лежащим в основе регрессии (p-value = 0.054)

# Если бы в этой строке было указано, что эти требования нарушены (p-value <0.05)
# пришлось бы исследовать данные, чтобы определить, какие именно требованя
# были нарушены
```

