---
title:,"R,Notebook"
output:,html_notebook
---

```{r}
first<-c(83,70,86,51,61,67,80,84,70,64,83,55,88,75,61,70,95,52,75,92,86,89,83,58,51,
65,87,54,90,62,67,66,83,65,70,87,69,51,51,60,52,74,80,79,85,85,92,22,92,57 ,84,92)

second <- c(70,31,70,46,78,69,36,33,65,70,74,51,90,26,62,70,86,86,80,33,55,31,69,31,62,
63,86,55,69,62,31,90,31,31,69,64,57,75,53,89,0,31,81,53,86,52,98,58,31,69,
69,51,75,39,0,56,51,69,46,41,65)
```

```{r}
cut1_1_first <- cut(first, breaks = c(0, 50, 68, 85, 100), labels = c("2", "3", "4", "5"))
cut1_2_first <- cut(first, breaks = c(0, 30, 50, 60, 68, 85, 95, 100), labels = c("F", "FX", "E",
                                                                            "D", "C", "B", "A"))
```

```{r}
cut1_1_first
cut1_2_first
```

```{r}
cut1_1_second <- cut(second, breaks = c(0, 50, 68, 85, 100), labels = c("2", "3", "4", "5"),
                     include.lowest=TRUE)
cut1_2_second <- cut(second, breaks = c(0, 30, 50, 60, 68, 85, 95, 100), labels = c("F", "FX", "E",
                                                                            "D", "C", "B", "A"),
                     include.lowest=TRUE)

cut1_1_second
cut1_2_second
```

```{r}
tab1_1_first <- table(cut1_1_first)
tab1_1_first
```

```{r}
tab1_2_first <- table(cut1_2_first)
tab1_2_first
```

```{r}
tab2_1_second <- table(cut1_1_second)
tab2_1_second
```

```{r}
tab2_1_first <- table(cut1_2_first)
tab2_1_first
```

```{r}
tab2_2_second <- table(cut1_2_second)
tab2_2_second
```

```{r}
#    5. Для каждого разбиения постройте таблицы относительных частот следующим образом:
#> table(разбиение1_1)/length(разбиение1_1)

table(cut1_1_first)/length(cut1_1_first)
table(cut1_2_first)/length(cut1_2_first)
table(cut1_1_second)/length(cut1_1_second)
table(cut1_2_second)/length(cut1_1_second)
```

```{r}
#    6. Постройте мозаичные диаграммы по созданным четырем таблицам таблица1_1 —
#таблица2_2 с помощью функции barplot(), т.е. когда height — числовой вектор. Разделите окно графика на 4 части (par(mfrow=c(2,2)).
#Пример:   barplot(height=таблица 1_1)

par(mfrow = c(2, 2))
barplot(height = tab1_1_first)
barplot(height = tab2_1_first)
barplot(height = tab2_1_second)
barplot(height = tab2_2_second)
```

```{r}
#Создайте матрицу (матрица1), объединив таблица1_1 и таблица2_1 используя функцию cbind().

cbind(tab1_1_first, tab1_2_first)
```

```{r}
cbind(tab2_1_second, tab2_2_second)
```

```{r}
#    9. Постройте мозаичные диаграммы по созданным матрицам (матрица1 и матрица2) с помощью функции barplot(), когда height — числовая матрица
#и beside = FALSE, разбив окно графика на 2 элемента (функция par()).
#Пример:   barplot(height=таблица3, beside=FALSE)
par(mfrow = c(2, 1))
barplot(height = cbind(tab1_1_first, tab1_2_first), besid = FALSE )
barplot(height = cbind(tab2_1_second, tab2_2_second), besid = FALSE )
```

```{r}
#    10. Постройте круговые диаграммы для таблиц таблица1_1 —таблица2_2, используя функцию pie() c аргументами: labels=c(), radius=1, col=c(), main=” ”; и разбив окно графика на 4 элемента (функция par()).
#Пример:
#pie(table1, labels=c(“2”,”3”,”4”), radius=1, col=c(5,15,26), main=” table1”)

par(mfrow = c(2, 2))
pie(tab1_1_first, labels=c("2","3","4"), radius=1, col=c(5,15,26), main= "tab1_1_first")
pie(tab1_2_first, labels=c("2","3","4"), radius=1, col=c(5,15,26), main= "tab1_2_first")
pie(tab2_1_second, labels=c("2","3","4"), radius=1, col=c(5,15,26), main= "tab2_1_second")
pie(tab2_2_second, labels=c("2","3","4"), radius=1, col=c(5,15,26), main= "tab2_2_second")
```




